services:
  postgres_database:
    image: postgres:latest
    restart: always
    container_name: postgres_w1_test_preparation
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: w1_test_preparation_app
    ports:
      - "8080:8080"
    depends_on:
      postgres_database:
        condition: service_healthy
    env_file:
      - .env.production
    volumes:
      - .:/app
      - /app/prisma

networks:
  prisma-network:

volumes:
  postgres_data:
